### ISSUE TITLE
info.json files make changes to the csproj (reported by Eagle3386)

### ISSUE THREAD

**Issue by renegadexx** [databinding-gmbh/T4.FileManager.VisualStudio#6] opened 2020-12-30 19:18 UTC
Hi Eagle3386

Can you please provide a t4 sample with details of Visual Studio, NuGet-Package and .NET Framework version, steps, a print screen, so that we can try to reproduce this issue.

**Comment by jgraber** [comment] 2021-01-24 19:19
I cannot reproduce this issue. If I generate the same files again, I cannot find any changes in *.info.json or the *.csproj file. 

Those files got changed on the first run / the first time I generated the files. Every generator run later on only modified *.info.json and *.csproj if I changed the files to generate or set additional properties (like CustomTool). In all other cases there was no modification.

Therefore, I close this issue. If Eagle3386 or anyone else has a code example that shows this behavior, I will gladly reopen this issue and try to fix it.

**Closed as completed by jgraber** 2021-01-24 19:19 UTC
